/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.view;

import br.edu.ifsp.control.FormapagamentoControle;
import br.edu.ifsp.control.PagamentoControle;
import br.edu.ifsp.model.EntidadesPagamento;
import br.edu.ifsp.model.FormaPagamento;
import br.edu.ifsp.model.Pagamento;
import br.edu.ifsp.util.FormatRenderer;
import br.edu.ifsp.util.NumberRenderer;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Murilo
 */
public class DialogPagamentos extends javax.swing.JDialog {

    ArrayList<FormaPagamento> listaFormaPagamento = new ArrayList<>();
    FormaPagamento formaPagamento = new FormaPagamento();
    FormapagamentoControle formaPagamentoControl = new FormapagamentoControle();

    PagamentoControle pagamentoControl = new PagamentoControle();
    Pagamento pagamento = new Pagamento();
    ArrayList<Pagamento> listaPagamento = new ArrayList<>();
    ArrayList<EntidadesPagamento> listaPagmentosVenda = new ArrayList<>();

    public DialogPagamentos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        centreWindow(this);

        listarFormaPagamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNomeCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCodigoVenda = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDataPedidoVenda = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTotalVenda = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblQtdPagamentoVenda = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListaPagamento = new javax.swing.JTable();
        cboxFormaPagamento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnQuitarParcela = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parcelas da venda");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Cliente:");

        lblNomeCliente.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblNomeCliente.setForeground(new java.awt.Color(153, 0, 0));
        lblNomeCliente.setText("nome");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Venda:");

        lblCodigoVenda.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblCodigoVenda.setForeground(new java.awt.Color(0, 153, 0));
        lblCodigoVenda.setText("codigo");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("Data do pedido:");

        lblDataPedidoVenda.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblDataPedidoVenda.setForeground(new java.awt.Color(0, 153, 0));
        lblDataPedidoVenda.setText("data pedido");

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setText("Total:");

        lblTotalVenda.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblTotalVenda.setForeground(new java.awt.Color(0, 153, 0));
        lblTotalVenda.setText("total");

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setText("Pagamentos:");

        lblQtdPagamentoVenda.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblQtdPagamentoVenda.setForeground(new java.awt.Color(0, 153, 0));
        lblQtdPagamentoVenda.setText("qtdpagmentos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de pagamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 14))); // NOI18N

        tableListaPagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Número", "Preço", "Data de Vencimento", "Data de Pagamento", "Forma de Pagamento", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableListaPagamento.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tableListaPagamento);
        if (tableListaPagamento.getColumnModel().getColumnCount() > 0) {
            tableListaPagamento.getColumnModel().getColumn(0).setMinWidth(0);
            tableListaPagamento.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        cboxFormaPagamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Forma de pagamento:");

        btnQuitarParcela.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnQuitarParcela.setForeground(new java.awt.Color(0, 153, 0));
        btnQuitarParcela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/check.png"))); // NOI18N
        btnQuitarParcela.setText("Quitar parcela");
        btnQuitarParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarParcelaActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/back.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCodigoVenda)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataPedidoVenda)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalVenda)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblQtdPagamentoVenda))
                            .addComponent(jLabel2)
                            .addComponent(cboxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltar)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitarParcela)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNomeCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCodigoVenda)
                    .addComponent(jLabel5)
                    .addComponent(lblDataPedidoVenda)
                    .addComponent(jLabel8)
                    .addComponent(lblTotalVenda)
                    .addComponent(jLabel10)
                    .addComponent(lblQtdPagamentoVenda))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuitarParcela)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitarParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarParcelaActionPerformed
        if (cboxFormaPagamento.getSelectedIndex() != 0) {
            String opt[] = {"Sim", "Não"};

            int op = JOptionPane.showOptionDialog(this, "Confirmar pagamento da parcela?", "Confirme a quitação da parcela", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opt, opt[1]);

            if (op == JOptionPane.YES_OPTION) {
                boolean anterior = true;

                for (int i = 0; i < tableListaPagamento.getRowCount(); i++) {
                    if ((tableListaPagamento.getValueAt(i, 6).equals("Pago")) && (!anterior)) {
                        anterior = true;
                    } else if (((tableListaPagamento.getValueAt(i, 6).equals("Pendente")) || (tableListaPagamento.getValueAt(i, 6).equals("Atrasado")))
                            && (anterior)) {
                        pagamento = new Pagamento();

                        pagamento.setCodigo(Integer.parseInt(String.valueOf(tableListaPagamento.getValueAt(i, 0))));
                        pagamento.setDatapagamento(new Date(System.currentTimeMillis()));
                        pagamento.setFormaPagamento(Integer.parseInt(cboxFormaPagamento.getSelectedItem().toString().split("-")[0]));
                        pagamento.setSituacao("Pago");

                        anterior = false;

                        pagamentoControl.quitarPagamento(pagamento);
                    }
                }
                exportarListaPagamento();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Defina a forma de pagamento no campo de seleção!");
        }
    }//GEN-LAST:event_btnQuitarParcelaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitarParcela;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cboxFormaPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoVenda;
    private javax.swing.JLabel lblDataPedidoVenda;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblQtdPagamentoVenda;
    private javax.swing.JLabel lblTotalVenda;
    private javax.swing.JTable tableListaPagamento;
    // End of variables declaration//GEN-END:variables

    public void exportarListaPagamento(ArrayList<EntidadesPagamento> listaPagmentosVenda) {
        DefaultTableModel modelo = (DefaultTableModel) tableListaPagamento.getModel();
        modelo.setNumRows(0);

        int cont = listaPagmentosVenda.size();

        SimpleDateFormat form = new SimpleDateFormat("dd/MM/yyyy");

        lblNomeCliente.setText(String.valueOf(listaPagmentosVenda.get(0).getClientesObj().getNome()));

        lblCodigoVenda.setText(String.valueOf(listaPagmentosVenda.get(0).getVendaObj().getCodigo()));
        lblDataPedidoVenda.setText(form.format(listaPagmentosVenda.get(0).getVendaObj().getDataPedido()));
        lblTotalVenda.setText("R$ " + String.valueOf(listaPagmentosVenda.get(0).getVendaObj().getTotal()).replace(".", ","));
        lblQtdPagamentoVenda.setText(String.valueOf(listaPagmentosVenda.get(0).getVendaObj().getQtdpagamento()));

        for (int i = 0; i < cont; i++) {

            formaPagamento = formaPagamentoControl.buscarCodigoFormaPagamento(String.valueOf(listaPagmentosVenda.get(i).getPagamentosObj().getFormaPagamento()));
            modelo.addRow(new Object[]{
                listaPagmentosVenda.get(i).getPagamentosObj().getCodigo(),
                listaPagmentosVenda.get(i).getPagamentosObj().getNumero(),
                listaPagmentosVenda.get(i).getPagamentosObj().getPreco(),
                listaPagmentosVenda.get(i).getPagamentosObj().getDatavencimento(),
                listaPagmentosVenda.get(i).getPagamentosObj().getDatapagamento(),
                formaPagamento.getForma(),
                listaPagmentosVenda.get(i).getPagamentosObj().getSituacao()
            });
        }
        organizarJtableVendas();
    }

    public void exportarListaPagamento() {
        DefaultTableModel modelo = (DefaultTableModel) tableListaPagamento.getModel();
        modelo.setNumRows(0);

        listaPagmentosVenda = new ArrayList<>();
        listaPagmentosVenda = pagamentoControl.consultarPagamentoVenda(lblCodigoVenda.getText());

        int cont = listaPagmentosVenda.size();

        SimpleDateFormat form = new SimpleDateFormat("dd/MM/yyyy");

        lblNomeCliente.setText(String.valueOf(listaPagmentosVenda.get(0).getClientesObj().getNome()));

        lblCodigoVenda.setText(String.valueOf(listaPagmentosVenda.get(0).getVendaObj().getCodigo()));
        lblDataPedidoVenda.setText(form.format(listaPagmentosVenda.get(0).getVendaObj().getDataPedido()));
        lblTotalVenda.setText("R$ " + String.valueOf(listaPagmentosVenda.get(0).getVendaObj().getTotal()).replace(".", ","));
        lblQtdPagamentoVenda.setText(String.valueOf(listaPagmentosVenda.get(0).getVendaObj().getQtdpagamento()));

        for (int i = 0; i < cont; i++) {

            formaPagamento = formaPagamentoControl.buscarCodigoFormaPagamento(String.valueOf(listaPagmentosVenda.get(i).getPagamentosObj().getFormaPagamento()));
            modelo.addRow(new Object[]{
                listaPagmentosVenda.get(i).getPagamentosObj().getCodigo(),
                listaPagmentosVenda.get(i).getPagamentosObj().getNumero(),
                listaPagmentosVenda.get(i).getPagamentosObj().getPreco(),
                listaPagmentosVenda.get(i).getPagamentosObj().getDatavencimento(),
                listaPagmentosVenda.get(i).getPagamentosObj().getDatapagamento(),
                formaPagamento.getForma(),
                listaPagmentosVenda.get(i).getPagamentosObj().getSituacao()
            });
        }
        organizarJtableVendas();
    }

    private void listarFormaPagamento() {
        listaFormaPagamento = formaPagamentoControl.listar();

        cboxFormaPagamento.removeAllItems();

        cboxFormaPagamento.addItem("- Selecione a Forma de Pagamento -");

        for (FormaPagamento listaFp : listaFormaPagamento) {
            cboxFormaPagamento.addItem(listaFp.toString());
        }
    }

    private void organizarJtableVendas() {
        tableListaPagamento.getColumnModel().getColumn(2).setCellRenderer(NumberRenderer.getCurrencyRenderer());
        tableListaPagamento.getColumnModel().getColumn(3).setCellRenderer(FormatRenderer.getDateRenderer());
        tableListaPagamento.getColumnModel().getColumn(4).setCellRenderer(NumberRenderer.getDateRenderer());
    }

    public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }
}
