/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.view;

import br.edu.ifsp.control.AcessoControle;
import br.edu.ifsp.model.Acesso;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Graphics;
import java.beans.PropertyVetoException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.SwingConstants;

/**
 *
 * @author Murilo
 */
public class FrameInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public FrameInicial() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

        btnVenda2.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnVenda2.setHorizontalTextPosition(SwingConstants.CENTER);

        btnCompra2.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnCompra2.setHorizontalTextPosition(SwingConstants.CENTER);

        btnOrcamento2.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnOrcamento2.setHorizontalTextPosition(SwingConstants.CENTER);

        btnRelatorios.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnRelatorios.setHorizontalTextPosition(SwingConstants.CENTER);

        btnCadastros.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnCadastros.setHorizontalTextPosition(SwingConstants.CENTER);

        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);

//        centralizarContainer(this, panelOperacao);
    }

    public void addTelaDesk(JInternalFrame nova) throws PropertyVetoException {
        for (JInternalFrame jInternalFrame : this.desktop.getAllFrames()) {
            jInternalFrame.setClosed(true);
        }
        centralizaForm(nova);
        desktop.add(nova); //adiciona na tela 
        nova.setVisible(true); // seta visivel   
    }

    private void centralizaForm(JInternalFrame frame) {
        Dimension desktopSize = this.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2, (desktopSize.height - jInternalFrameSize.height) / 3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/br/edu/ifsp/icons/bike_conecta-1200.jpg"));
        Image image = icon.getImage();
        desktop = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }

        };
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblNomeUser = new javax.swing.JLabel();
        lblCodUser = new javax.swing.JLabel();
        lblNomeUser2 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnCadastros = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnOrcamento2 = new javax.swing.JButton();
        btnCompra2 = new javax.swing.JButton();
        btnVenda2 = new javax.swing.JButton();
        lblCodAcesso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Ciclo Bike – Vendas e Serviços de Oficina Bicicletas");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblUsuario.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        lblUsuario.setText("Usuário");

        lblData.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        lblData.setText("Data");

        lblNomeUser.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        lblNomeUser.setText("Nome");

        lblCodUser.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        lblCodUser.setText("Código");

        lblNomeUser2.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        lblNomeUser2.setText("-");

        btnFechar.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/cruz.png"))); // NOI18N
        btnFechar.setText("Sair");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnCadastros.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btnCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/pencil.png"))); // NOI18N
        btnCadastros.setText("Cadastros");
        btnCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrosActionPerformed(evt);
            }
        });

        btnRelatorios.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/relatorio.png"))); // NOI18N
        btnRelatorios.setText("Relátorios");
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });

        btnOrcamento2.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btnOrcamento2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/orcamento.png"))); // NOI18N
        btnOrcamento2.setText("Orçamento");
        btnOrcamento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrcamento2ActionPerformed(evt);
            }
        });

        btnCompra2.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btnCompra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/inventory.png"))); // NOI18N
        btnCompra2.setText("Compra");
        btnCompra2.setToolTipText("");
        btnCompra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompra2ActionPerformed(evt);
            }
        });

        btnVenda2.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btnVenda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/iconfinder_shopping_basket red_10529.png"))); // NOI18N
        btnVenda2.setText("Venda");
        btnVenda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenda2ActionPerformed(evt);
            }
        });

        lblCodAcesso.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeUser2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeUser)
                        .addGap(462, 462, 462)
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                        .addComponent(lblCodAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(324, 324, 324)
                        .addComponent(lblData)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnVenda2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCompra2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFechar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOrcamento2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRelatorios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCadastros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktop))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCodAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblUsuario)
                        .addComponent(lblNomeUser)
                        .addComponent(lblCodUser)
                        .addComponent(lblNomeUser2)
                        .addComponent(lblData)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVenda2)
                        .addGap(18, 18, 18)
                        .addComponent(btnCompra2)
                        .addGap(18, 18, 18)
                        .addComponent(btnOrcamento2)
                        .addGap(18, 18, 18)
                        .addComponent(btnRelatorios)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastros)
                        .addGap(30, 30, 30)
                        .addComponent(btnFechar)
                        .addContainerGap())
                    .addComponent(desktop)))
        );

        setSize(new java.awt.Dimension(1377, 906));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.MEDIUM);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void btnVenda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenda2ActionPerformed
        InterFazerVenda internal = new InterFazerVenda();

        try {
            addTelaDesk(internal);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrameInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVenda2ActionPerformed

    private void btnCompra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompra2ActionPerformed
        InterCompra internal = new InterCompra();

        try {
            addTelaDesk(internal);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrameInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCompra2ActionPerformed

    private void btnOrcamento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrcamento2ActionPerformed
        InterFazerOrcamento internal = new InterFazerOrcamento();

        try {
            addTelaDesk(internal);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrameInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOrcamento2ActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        InterRelatorios internal = new InterRelatorios();

        try {
            addTelaDesk(internal);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrameInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrosActionPerformed
        InterCadastros internal = new InterCadastros();

        try {
            addTelaDesk(internal);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrameInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCadastrosActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        String opt[] = {"Sim", "Não"};

        int sair = JOptionPane.showOptionDialog(this, "Sair do Sistema?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opt, opt[1]);

        if (sair == JOptionPane.YES_OPTION) {
            finalizarAcesso();

            System.exit(0);
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String opt[] = {"Sim", "Não"};

        int sair = JOptionPane.showOptionDialog(this, "Sair do Sistema?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opt, opt[1]);

        if (sair == JOptionPane.YES_OPTION) {
            finalizarAcesso();

            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCadastros;
    public static javax.swing.JButton btnCompra2;
    private javax.swing.JButton btnFechar;
    public static javax.swing.JButton btnOrcamento2;
    public static javax.swing.JButton btnRelatorios;
    public static javax.swing.JButton btnVenda2;
    public static javax.swing.JDesktopPane desktop;
    public static javax.swing.JLabel lblCodAcesso;
    public static javax.swing.JLabel lblCodUser;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblNomeUser;
    public static javax.swing.JLabel lblNomeUser2;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables

    private void centralizarContainer(Component pai, Component filho) {
        // obter dimensões do pai
        int larguraPai = pai.getWidth();
        int alturaPai = pai.getHeight();

        // obter dimensões do filho
        int larguraFilho = filho.getWidth();
        int alturaFilho = filho.getWidth();

        // calcular novas coordenadas do filho  
        int novoX = (larguraPai - larguraFilho);
        int novoY = (alturaPai - alturaFilho);

        // centralizar filho
        filho.getParent().setLayout(new GridBagLayout());
        filho.setSize(new Dimension(novoX, novoY));
        filho.repaint();
    }

    private void finalizarAcesso() {
        AcessoControle acessControl = new AcessoControle();
        Acesso acesso = new Acesso();

        acesso.setCodAcesso(Integer.valueOf(FrameInicial.lblCodAcesso.getText()));
        acesso.setCodFuncionario(Integer.valueOf(FrameInicial.lblCodUser.getText()));
        acesso.setHorarioEntrada(LocalDateTime.now());

        acessControl.atualizarSaida(acesso);
    }
}
