/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.view;

import br.edu.ifsp.connection.Conexao;
import br.edu.ifsp.control.FormapagamentoControle;
import br.edu.ifsp.model.FormaPagamento;
import java.awt.Component;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Murilo
 */
public class InterCadFormaPagamento extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    private boolean novo;
    private int rowSelectedInTable = -1;

    public InterCadFormaPagamento() {
        initComponents();

        conexao = Conexao.abrir();

        listaFormaPagamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollFrameFormaPagamento = new javax.swing.JScrollPane();
        panelFormaPagamento = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtForma = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFormaPagamento = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Forma de Pagamento");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Forma de Pagamento");

        btnVoltar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Forma de Pagamento *");

        txtForma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtForma.setEnabled(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/pesquisar.png"))); // NOI18N

        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setEnabled(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo)
                .addGap(18, 18, 18)
                .addComponent(btnGravar)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(121, 121, 121)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tableFormaPagamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableFormaPagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableFormaPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFormaPagamentoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableFormaPagamento);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Descrição *");

        txtDescricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDescricao.setEnabled(false);

        javax.swing.GroupLayout panelFormaPagamentoLayout = new javax.swing.GroupLayout(panelFormaPagamento);
        panelFormaPagamento.setLayout(panelFormaPagamentoLayout);
        panelFormaPagamentoLayout.setHorizontalGroup(
            panelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormaPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormaPagamentoLayout.createSequentialGroup()
                        .addGroup(panelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelFormaPagamentoLayout.createSequentialGroup()
                        .addGroup(panelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(panelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtForma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelFormaPagamentoLayout.setVerticalGroup(
            panelFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormaPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtForma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollFrameFormaPagamento.setViewportView(panelFormaPagamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollFrameFormaPagamento)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollFrameFormaPagamento)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCampos();
        btnNovo.setEnabled(true);
        btnAlterar.setEnabled(true);
        habilitarCampos(false);
        btnGravar.setEnabled(false);
        btnCancelar.setEnabled(false);
        tableFormaPagamento.setEnabled(true);
        tableFormaPagamento.clearSelection();
        rowSelectedInTable = -1;
        txtPesquisa.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        novo = true;

        btnNovo.setEnabled(false);
        btnAlterar.setEnabled(false);
        habilitarCampos(true);
        limparCampos();
        btnGravar.setEnabled(true);
        btnCancelar.setEnabled(true);

        tableFormaPagamento.setEnabled(false);
        tableFormaPagamento.clearSelection();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(InterCadFormaPagamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        adicionar();
        rowSelectedInTable = -1;
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (rowSelectedInTable != -1) {
            novo = false;

            btnNovo.setEnabled(false);
            btnAlterar.setEnabled(false);
            habilitarCampos(true);
            btnGravar.setEnabled(true);
            btnCancelar.setEnabled(true);
            
            tableFormaPagamento.setEnabled(false);
            tableFormaPagamento.setRowSelectionInterval(rowSelectedInTable, rowSelectedInTable);
            
            txtPesquisa.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma forma de pagamento da lista!", "Alteração de Dados", 1);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tableFormaPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFormaPagamentoMouseClicked
        setCampos();
    }//GEN-LAST:event_tableFormaPagamentoMouseClicked

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        pesquisarFormaPagamento();
    }//GEN-LAST:event_txtPesquisaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelFormaPagamento;
    private javax.swing.JScrollPane scrollFrameFormaPagamento;
    private javax.swing.JTable tableFormaPagamento;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtForma;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

    private void organizarJtable() {
        tableFormaPagamento.setDefaultEditor(Object.class, null);

        tableFormaPagamento.getColumnModel().getColumn(0).setMinWidth(0);
        tableFormaPagamento.getColumnModel().getColumn(0).setMaxWidth(0);

        tableFormaPagamento.getColumnModel().getColumn(1).setHeaderValue("Forma de pagamento");
        tableFormaPagamento.getColumnModel().getColumn(2).setHeaderValue("Descrição");
    }

    private void listaFormaPagamento() {
        String sql = "SELECT * FROM formapagamento";

        try {
            pst = conexao.prepareStatement(sql);

            rs = pst.executeQuery();

            tableFormaPagamento.setModel(DbUtils.resultSetToTableModel(rs));

            organizarJtable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void pesquisarFormaPagamento() {
        String sql = "SELECT * FROM formapagamento WHERE forma LIKE ?";

        try {
            pst = conexao.prepareStatement(sql);

            pst.setString(1, "%" + txtPesquisa.getText() + "%");

            rs = pst.executeQuery();

            tableFormaPagamento.setModel(DbUtils.resultSetToTableModel(rs));

            organizarJtable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void limparCampos() {
        txtForma.setText(null);
        txtDescricao.setText(null);
    }

    private void habilitarCampos(boolean habilita) {
        txtForma.setEnabled(habilita);
        txtDescricao.setEnabled(habilita);
    }

    private void adicionar() {
        if ((txtForma.getText().isEmpty()) || (txtDescricao.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios (*) !");
        } else {
            int op = JOptionPane.showInternalConfirmDialog(getInstance(), "Prosseguir com as inserções feitas?", "Registro da forma de pagamento",
                    JOptionPane.YES_NO_OPTION);

            if (op == JOptionPane.YES_NO_OPTION) {
                FormaPagamento formPagamento = new FormaPagamento();

                FormapagamentoControle fpControl = new FormapagamentoControle();

                formPagamento.setForma(txtForma.getText());
                formPagamento.setDescricao(txtDescricao.getText());

                if (novo) {
                    fpControl.adicionar(formPagamento);
                } else {
                    formPagamento.setCodigo(Integer.parseInt(tableFormaPagamento.getModel().getValueAt(rowSelectedInTable, 0).toString()));
                    fpControl.atualizar(formPagamento);
                }

                limparCampos();

                tableFormaPagamento.setEnabled(true);
                btnNovo.setEnabled(true);
                btnAlterar.setEnabled(true);

                habilitarCampos(false);

                btnGravar.setEnabled(false);
                btnCancelar.setEnabled(false);
                
                txtPesquisa.setEnabled(true);

                listaFormaPagamento();
            }
        }
    }

    private Component getInstance() {
        return this;
    }

    private void setCampos() {
        rowSelectedInTable = tableFormaPagamento.getSelectedRow();

        txtForma.setText(tableFormaPagamento.getModel().getValueAt(rowSelectedInTable, 1).toString());
        txtDescricao.setText(tableFormaPagamento.getModel().getValueAt(rowSelectedInTable, 2).toString());
    }

//    private void excluir() {
//        int confirma = JOptionPane.showConfirmDialog(null, "Remover esta forma de pagamento?", "Atenção", JOptionPane.YES_NO_OPTION);
//
//        if (confirma == JOptionPane.YES_OPTION) {
//            FormaPagamento formPagamento = new FormaPagamento();
//
//            FormapagamentoControle fpControl = new FormapagamentoControle();
//
//            formPagamento.setForma(txtForma.getText());
//            formPagamento.setDescricao(txtDescricao.getText());
//
//            formPagamento.setCodigo(Integer.parseInt(tableFormaPagamento.getModel().getValueAt(tableFormaPagamento.getSelectedRow(), 0).toString()));
//
//            fpControl.excluir(formPagamento);
//
//            limparCampos();
//
//            listaFormaPagamento();
//        }
//    }

}
