/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.view;

import br.edu.ifsp.connection.Conexao;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Murilo
 */
public class InterRelatorios extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterRelatorios
     */
    public InterRelatorios() {
        initComponents();

        btnRelProdutos.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnRelProdutos.setHorizontalTextPosition(SwingConstants.CENTER);

        btnRelFuncionarioUsuario.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnRelFuncionarioUsuario.setHorizontalTextPosition(SwingConstants.CENTER);

        btnRelParcelas.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnRelParcelas.setHorizontalTextPosition(SwingConstants.CENTER);

        btnRelAcessos.setVerticalTextPosition(SwingConstants.BOTTOM);
        btnRelAcessos.setHorizontalTextPosition(SwingConstants.CENTER);
        
        if (!FrameInicial.lblUsuario.getText().equals("administrador")) {
            btnRelAcessos.setEnabled(false);
            btnRelFuncionarioUsuario.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRelProdutos = new javax.swing.JButton();
        btnRelFuncionarioUsuario = new javax.swing.JButton();
        btnRelParcelas = new javax.swing.JButton();
        btnRelAcessos = new javax.swing.JButton();

        setClosable(true);
        setTitle("Relatórios");

        btnRelProdutos.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btnRelProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/bicicleta.png"))); // NOI18N
        btnRelProdutos.setText("Relatório de Produtos");
        btnRelProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelProdutosActionPerformed(evt);
            }
        });

        btnRelFuncionarioUsuario.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btnRelFuncionarioUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/grupo-de-usuarios.png"))); // NOI18N
        btnRelFuncionarioUsuario.setText("Relatório de Usuario/Funcionários");
        btnRelFuncionarioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelFuncionarioUsuarioActionPerformed(evt);
            }
        });

        btnRelParcelas.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btnRelParcelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/relatorio (2).png"))); // NOI18N
        btnRelParcelas.setText("Relatório de Parcelas Pendentes");
        btnRelParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelParcelasActionPerformed(evt);
            }
        });

        btnRelAcessos.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        btnRelAcessos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/autenticacao.png"))); // NOI18N
        btnRelAcessos.setText("Relatório de Acessos");
        btnRelAcessos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelAcessosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRelParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(btnRelProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRelFuncionarioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelAcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelProdutos)
                    .addComponent(btnRelFuncionarioUsuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelParcelas)
                    .addComponent(btnRelAcessos))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelProdutosActionPerformed
        try {
            JasperReport relCompilado = JasperCompileManager.compileReport("src/br/edu/ifsp/rel/RelatorioProduto.jrxml");

            JasperPrint relPreenchido = JasperFillManager.fillReport(relCompilado, null, Conexao.abrir());

            JFrame tela = new JFrame("Relatório de Vendas por Período");
            tela.setSize(1080, 720);

            JRViewer painelRelatorio = new JRViewer(relPreenchido);

            tela.getContentPane().add(painelRelatorio);

            tela.setVisible(true);

        } catch (JRException ex) {
            java.util.logging.Logger.getLogger(InterRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao gerar Relatório de Venda");
        }
    }//GEN-LAST:event_btnRelProdutosActionPerformed

    private void btnRelFuncionarioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelFuncionarioUsuarioActionPerformed
        try {
            JasperReport relCompilado = JasperCompileManager.compileReport("src/br/edu/ifsp/rel/RelatorioUsuario.jrxml");

            JasperPrint relPreenchido = JasperFillManager.fillReport(relCompilado, null, Conexao.abrir());

            JFrame tela = new JFrame("Relatório de Usuários");
            tela.setSize(1080, 720);

            JRViewer painelRelatorio = new JRViewer(relPreenchido);

            tela.getContentPane().add(painelRelatorio);

            tela.setVisible(true);

        } catch (JRException ex) {
            java.util.logging.Logger.getLogger(InterRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao gerar Relatório de Usuários");
        }
    }//GEN-LAST:event_btnRelFuncionarioUsuarioActionPerformed

    private void btnRelParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelParcelasActionPerformed
        DialogRelParcelasPendentes dialog = new DialogRelParcelasPendentes(new Frame(), true);

        dialog.setVisible(true);
    }//GEN-LAST:event_btnRelParcelasActionPerformed

    private void btnRelAcessosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelAcessosActionPerformed
        DialogRelAcessos dialog = new DialogRelAcessos(new Frame(), true);

        dialog.setVisible(true);
    }//GEN-LAST:event_btnRelAcessosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRelAcessos;
    private javax.swing.JButton btnRelFuncionarioUsuario;
    private javax.swing.JButton btnRelParcelas;
    private javax.swing.JButton btnRelProdutos;
    // End of variables declaration//GEN-END:variables

}
