/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.view;

import br.edu.ifsp.connection.Conexao;
import br.edu.ifsp.control.ServicoControle;
import br.edu.ifsp.util.NumberRenderer;
import br.edu.ifsp.model.Servico;
import java.awt.Component;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Murilo
 */
public class InterCadServico extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    private boolean novo;
    private int rowSelectedInTable = -1;

    public InterCadServico() {
        initComponents();

        conexao = Conexao.abrir();

        listaServico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollFrameServico = new javax.swing.JScrollPane();
        panelServico = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableServico = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        ftxtPreco = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Serviço");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Serviço");

        btnVoltar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Descrição *");

        txtDescricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDescricao.setEnabled(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/pesquisar.png"))); // NOI18N

        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setEnabled(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo)
                .addGap(18, 18, 18)
                .addComponent(btnGravar)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(121, 121, 121)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tableServico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableServicoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableServico);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setText("Preço (R$) *");

        ftxtPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        ftxtPreco.setEnabled(false);
        ftxtPreco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ftxtPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtPrecoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panelServicoLayout = new javax.swing.GroupLayout(panelServico);
        panelServico.setLayout(panelServicoLayout);
        panelServicoLayout.setHorizontalGroup(
            panelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelServicoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelServicoLayout.createSequentialGroup()
                        .addGroup(panelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(panelServicoLayout.createSequentialGroup()
                                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panelServicoLayout.createSequentialGroup()
                        .addGroup(panelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(ftxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelServicoLayout.setVerticalGroup(
            panelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        scrollFrameServico.setViewportView(panelServico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollFrameServico)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollFrameServico, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCampos();
        btnNovo.setEnabled(true);
        btnAlterar.setEnabled(true);
        habilitarCampos(false);
        btnGravar.setEnabled(false);
        btnCancelar.setEnabled(false);
        tableServico.setEnabled(true);
        tableServico.clearSelection();
        rowSelectedInTable = -1;
        txtPesquisa.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        pesquisarServico();
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            java.util.logging.Logger.getLogger(InterCadServico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        novo = true;

        btnNovo.setEnabled(false);
        btnAlterar.setEnabled(false);
        habilitarCampos(true);
        limparCampos();
        btnGravar.setEnabled(true);
        btnCancelar.setEnabled(true);

        tableServico.setEnabled(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        adicionar();
        rowSelectedInTable = -1;
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (rowSelectedInTable != -1) {
            novo = false;

            btnNovo.setEnabled(false);
            btnAlterar.setEnabled(false);
            habilitarCampos(true);
            btnGravar.setEnabled(true);
            btnCancelar.setEnabled(true);
            tableServico.setEnabled(false);
            tableServico.clearSelection();
            txtPesquisa.setEnabled(false);

            tableServico.setRowSelectionInterval(rowSelectedInTable, rowSelectedInTable);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um serviço da lista!", "Alteração de Dados", 1);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tableServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableServicoMouseClicked
        setCampos();
    }//GEN-LAST:event_tableServicoMouseClicked

    private void ftxtPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtPrecoFocusLost
//        String sv = ftxtPreco.getText();
//        System.out.println("1° " + sv);
//
//        String vf = sv.replaceAll("R$", "").replaceAll(" ", "").replaceAll("\\.", "").replaceAll(",", ".");
//        System.out.println("2° " + vf);
//
//        BigDecimal valor = new BigDecimal(vf);
//        System.out.println("3° " + valor);
//
//        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
//
//        String valorFormatado = nf.format(valor);
//        System.out.println("3° " + valorFormatado);
//
//        ftxtPreco.setText(valorFormatado);
//
//        System.out.println(valor);
    }//GEN-LAST:event_ftxtPrecoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFormattedTextField ftxtPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelServico;
    private javax.swing.JScrollPane scrollFrameServico;
    private javax.swing.JTable tableServico;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

    private void organizarJtable() {
        tableServico.setDefaultEditor(Object.class, null);

        tableServico.getColumnModel().getColumn(0).setMinWidth(0);
        tableServico.getColumnModel().getColumn(0).setMaxWidth(0);

        tableServico.getColumnModel().getColumn(1).setHeaderValue("Descrição");
        tableServico.getColumnModel().getColumn(2).setHeaderValue("Preço");

        tableServico.getColumnModel().getColumn(2).setCellRenderer(NumberRenderer.getCurrencyRenderer());
    }

    private void listaServico() {
        String sql = "SELECT * FROM servico";

        try {
            pst = conexao.prepareStatement(sql);

            rs = pst.executeQuery();

            tableServico.setModel(DbUtils.resultSetToTableModel(rs));

            organizarJtable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void pesquisarServico() {
        String sql = "SELECT * FROM servico WHERE descricao LIKE ?";

        try {
            pst = conexao.prepareStatement(sql);

            pst.setString(1, "%" + txtPesquisa.getText() + "%");

            rs = pst.executeQuery();

            tableServico.setModel(DbUtils.resultSetToTableModel(rs));

            organizarJtable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void limparCampos() {
        txtDescricao.setText(null);
        ftxtPreco.setText(null);
    }

    private void habilitarCampos(boolean habilita) {
        txtDescricao.setEnabled(habilita);
        ftxtPreco.setEnabled(habilita);
    }

    private void adicionar() {
        if ((txtDescricao.getText().isEmpty()) || (ftxtPreco.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios (*) !");
        }else if (0 > Double.parseDouble(ftxtPreco.getText().replace(".", "").replace(",", "."))) {
            JOptionPane.showMessageDialog(null, "Não informe valores abaixo que Zero (*) !");
        } else {
            int op = JOptionPane.showInternalConfirmDialog(getInstance(), "Prosseguir com as inserções feitas?", "Registro da serviço",
                    JOptionPane.YES_NO_OPTION);

            if (op == JOptionPane.YES_NO_OPTION) {
                Servico servico = new Servico();

                ServicoControle servControl = new ServicoControle();

//                String sv = ftxtPreco.getText();
//                System.out.println("1° " + sv);
//                String vf = sv.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
//                System.out.println("2° " + vf);
//                BigDecimal valor = new BigDecimal(vf);
//                System.out.println("3° " + valor);
                String sv = ftxtPreco.getText();
                String vf = sv.replace(".", "").replace(",", ".");

                servico.setDescricao(txtDescricao.getText());
                servico.setPreco(Double.parseDouble(vf));

                if (novo) {
                    servControl.adcionar(servico);
                } else {
                    servico.setCodigo(Integer.parseInt(tableServico.getModel().getValueAt(rowSelectedInTable, 0).toString()));
                    servControl.atualizar(servico);
                }

                limparCampos();

                tableServico.setEnabled(true);
                btnNovo.setEnabled(true);
                btnAlterar.setEnabled(true);

                habilitarCampos(false);

                btnGravar.setEnabled(false);
                btnCancelar.setEnabled(false);

                txtPesquisa.setEnabled(true);

                listaServico();
            }
        }
    }

    private Component getInstance() {
        return this;
    }

    private void setCampos() {
        rowSelectedInTable = tableServico.getSelectedRow();

        txtDescricao.setText(tableServico.getModel().getValueAt(rowSelectedInTable, 1).toString());

        String preco = tableServico.getModel().getValueAt(rowSelectedInTable, 2).toString();
        String precoFormat = preco.replace("R$", "").replace(" ", "").replace(".", ",");
        ftxtPreco.setText(precoFormat);
    }
}
