/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.view;

import br.edu.ifsp.connection.Conexao;
import br.edu.ifsp.control.FornecedorControle;
import br.edu.ifsp.model.Fornecedor;
import br.edu.ifsp.util.SoNumero;
import br.edu.ifsp.util.ValidarCnpj;
import java.awt.Component;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Murilo
 */
public class InterCadFornecedor extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    private boolean novo;
    private int rowSelectedInTable = -1;

    public InterCadFornecedor() {
        initComponents();

        txtNumero.setDocument(new SoNumero());
        txtTelefone.setDocument(new SoNumero());
        txtTelefoneSec.setDocument(new SoNumero());

        conexao = Conexao.abrir();

        listaFornecedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollFrameFornecedor = new javax.swing.JScrollPane();
        panelFornecedor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNomeFantasia = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        ftxtCnpj = new javax.swing.JFormattedTextField();
        ftxtCep = new javax.swing.JFormattedTextField();
        cboxUf = new javax.swing.JComboBox<>();
        ftxtDdd = new javax.swing.JFormattedTextField();
        ftxtDddSec = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFornecedor = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtContato = new javax.swing.JTextField();
        txtContatoSec = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtTelefoneSec = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Fornecedor");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Fornecedor");

        btnVoltar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Nome Fantasia *");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("Endereço *");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Telefone *");

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setText("Bairro *");

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setText("UF *");

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setText("CNPJ *");

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setText("CEP *");

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel11.setText("Número *");

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel12.setText("Cidade *");

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel13.setText("Telefone Secundário");

        txtNomeFantasia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomeFantasia.setEnabled(false);

        txtEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEndereco.setEnabled(false);

        txtNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNumero.setEnabled(false);

        txtBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBairro.setEnabled(false);

        txtCidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCidade.setEnabled(false);

        try {
            ftxtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCnpj.setEnabled(false);
        ftxtCnpj.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        try {
            ftxtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCep.setEnabled(false);
        ftxtCep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cboxUf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboxUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione um estado --", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cboxUf.setEnabled(false);

        try {
            ftxtDdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtDdd.setEnabled(false);
        ftxtDdd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        try {
            ftxtDddSec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtDddSec.setEnabled(false);
        ftxtDddSec.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsp/icons/pesquisar.png"))); // NOI18N

        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnGravar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setEnabled(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo)
                .addGap(18, 18, 18)
                .addComponent(btnGravar)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(121, 121, 121)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tableFornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFornecedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableFornecedor);

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel14.setText("Contato *");

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel15.setText("Contato Secundário");

        txtContato.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtContato.setEnabled(false);

        txtContatoSec.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtContatoSec.setEnabled(false);

        txtTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefone.setEnabled(false);

        txtTelefoneSec.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefoneSec.setEnabled(false);

        javax.swing.GroupLayout panelFornecedorLayout = new javax.swing.GroupLayout(panelFornecedor);
        panelFornecedor.setLayout(panelFornecedorLayout);
        panelFornecedorLayout.setHorizontalGroup(
            panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFornecedorLayout.createSequentialGroup()
                        .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNomeFantasia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(ftxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(408, 408, 408))
                    .addGroup(panelFornecedorLayout.createSequentialGroup()
                        .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(panelFornecedorLayout.createSequentialGroup()
                        .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFornecedorLayout.createSequentialGroup()
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFornecedorLayout.createSequentialGroup()
                                .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(ftxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addGroup(panelFornecedorLayout.createSequentialGroup()
                                        .addComponent(ftxtDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(141, 141, 141)
                                .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFornecedorLayout.createSequentialGroup()
                                        .addComponent(ftxtDddSec, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTelefoneSec, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(cboxUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtContatoSec, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 275, Short.MAX_VALUE))))
        );
        panelFornecedorLayout.setVerticalGroup(
            panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxUf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftxtDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftxtDddSec, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefoneSec, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContatoSec, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        scrollFrameFornecedor.setViewportView(panelFornecedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollFrameFornecedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollFrameFornecedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(InterCadFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCampos();
        btnNovo.setEnabled(true);
        btnAlterar.setEnabled(true);
        habilitarCampos(false);
        btnGravar.setEnabled(false);
        btnCancelar.setEnabled(false);
        tableFornecedor.setEnabled(true);
        tableFornecedor.clearSelection();
        rowSelectedInTable = -1;
        txtPesquisa.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        pesquisarFornecedor();
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        novo = true;

        btnNovo.setEnabled(false);
        btnAlterar.setEnabled(false);
        habilitarCampos(true);
        limparCampos();
        btnGravar.setEnabled(true);
        btnCancelar.setEnabled(true);

        tableFornecedor.setEnabled(false);
        tableFornecedor.clearSelection();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        adicionar();
        rowSelectedInTable = -1;
    }//GEN-LAST:event_btnGravarActionPerformed

    private void tableFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFornecedorMouseClicked
        setCampos();
    }//GEN-LAST:event_tableFornecedorMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
// chamando metodos para alterar informação de um cliente
        if (rowSelectedInTable != -1) {
            novo = false;

            btnNovo.setEnabled(false);
            btnAlterar.setEnabled(false);
            habilitarCampos(true);
            btnGravar.setEnabled(true);
            btnCancelar.setEnabled(true);
            
            tableFornecedor.setEnabled(false);            
            tableFornecedor.setRowSelectionInterval(rowSelectedInTable, rowSelectedInTable);
            
            txtPesquisa.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um fornecedor da lista!", "Alteração de Dados", 1);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cboxUf;
    private javax.swing.JFormattedTextField ftxtCep;
    private javax.swing.JFormattedTextField ftxtCnpj;
    private javax.swing.JFormattedTextField ftxtDdd;
    private javax.swing.JFormattedTextField ftxtDddSec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelFornecedor;
    private javax.swing.JScrollPane scrollFrameFornecedor;
    private javax.swing.JTable tableFornecedor;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtContatoSec;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTelefoneSec;
    // End of variables declaration//GEN-END:variables

    public void resizeColumnWidth(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 15; // Min width
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 1, width);
            }
            if (width > 300) {
                width = 300;
            }
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }

    private void organizarJtable() {
        tableFornecedor.setDefaultEditor(Object.class, null);

        tableFornecedor.getColumnModel().getColumn(0).setMinWidth(0);
        tableFornecedor.getColumnModel().getColumn(0).setMaxWidth(0);

        tableFornecedor.getColumnModel().getColumn(1).setHeaderValue("Nome fantasia");
        tableFornecedor.getColumnModel().getColumn(2).setHeaderValue("CNPJ");
        tableFornecedor.getColumnModel().getColumn(3).setHeaderValue("Endereço");
        tableFornecedor.getColumnModel().getColumn(4).setHeaderValue("Numero");
        tableFornecedor.getColumnModel().getColumn(5).setHeaderValue("Bairro");
        tableFornecedor.getColumnModel().getColumn(6).setHeaderValue("Cidade");
        tableFornecedor.getColumnModel().getColumn(7).setHeaderValue("CEP");
        tableFornecedor.getColumnModel().getColumn(8).setHeaderValue("UF");
        tableFornecedor.getColumnModel().getColumn(9).setHeaderValue("Telefone");
        tableFornecedor.getColumnModel().getColumn(10).setHeaderValue("Telefone Sec.");
        tableFornecedor.getColumnModel().getColumn(11).setHeaderValue("Contato");
        tableFornecedor.getColumnModel().getColumn(12).setHeaderValue("Contato sec.");

        resizeColumnWidth(tableFornecedor);
    }

    private void listaFornecedor() {
        String sql = "SELECT * FROM fornecedor";

        try {
            pst = conexao.prepareStatement(sql);

            rs = pst.executeQuery();

            tableFornecedor.setModel(DbUtils.resultSetToTableModel(rs));

            organizarJtable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void pesquisarFornecedor() {
        String sql = "SELECT * FROM fornecedor WHERE nomefantasia LIKE ?";

        try {
            pst = conexao.prepareStatement(sql);

            pst.setString(1, "%" + txtPesquisa.getText() + "%");

            rs = pst.executeQuery();

            tableFornecedor.setModel(DbUtils.resultSetToTableModel(rs));

            organizarJtable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void limparCampos() {
        txtNomeFantasia.setText(null);
        ftxtCnpj.setText(null);
        txtEndereco.setText(null);
        txtNumero.setText(null);
        txtBairro.setText(null);
        txtCidade.setText(null);
        ftxtCep.setText(null);
        cboxUf.setSelectedIndex(0);
        ftxtDdd.setText(null);
        txtTelefone.setText(null);
        ftxtDddSec.setText(null);
        txtTelefoneSec.setText(null);
        txtContato.setText(null);
        txtContatoSec.setText(null);
    }

    private void habilitarCampos(boolean habilita) {
        txtNomeFantasia.setEnabled(habilita);
//        ftxtCnpj.setEnabled(habilita);
        txtEndereco.setEnabled(habilita);
        txtNumero.setEnabled(habilita);
        txtBairro.setEnabled(habilita);
        txtCidade.setEnabled(habilita);
        ftxtCep.setEnabled(habilita);
        cboxUf.setEnabled(habilita);
        ftxtDdd.setEnabled(habilita);
        txtTelefone.setEnabled(habilita);
        ftxtDddSec.setEnabled(habilita);
        txtTelefoneSec.setEnabled(habilita);
        txtContato.setEnabled(habilita);
        txtContatoSec.setEnabled(habilita);
    }

    private void adicionar() {
        FornecedorControle fornControl = new FornecedorControle();

        if ((txtNomeFantasia.getText().isEmpty()) || (ftxtCnpj.getText().isEmpty())
                || (txtEndereco.getText().isEmpty()) || (txtNumero.getText().isEmpty()) || (txtBairro.getText().isEmpty()) || (txtCidade.getText().isEmpty())
                || (cboxUf.getSelectedIndex() == 0) || (ftxtCep.getText().isEmpty()) || (ftxtDdd.getText().isEmpty()) || (txtTelefone.getText().isEmpty())
                || (txtContato.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios (*) !");
        } else if (ValidarCnpj.isCNPJ(ftxtCnpj.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Número de CPF é inválido (*) !");
        } else {
            int op = JOptionPane.showInternalConfirmDialog(getInstance(), "Prosseguir com as inserções feitas?", "Registro de fornecedor",
                    JOptionPane.YES_NO_OPTION);

            if (op == JOptionPane.YES_NO_OPTION) {
                Fornecedor fornecedor = new Fornecedor();

                String numContato = ftxtDdd.getText() + " " + txtTelefone.getText();
                String numContatoSec = ftxtDddSec.getText() + " " + txtTelefoneSec.getText();

                System.out.println(numContato);

                fornecedor.setNomefantasia(txtNomeFantasia.getText());
                fornecedor.setCnpj(ftxtCnpj.getText());
                fornecedor.setEndereco(txtEndereco.getText());
                fornecedor.setNumero(txtNumero.getText());
                fornecedor.setBairro(txtBairro.getText());
                fornecedor.setCidade(txtCidade.getText());
                fornecedor.setCep(ftxtCep.getText());
                fornecedor.setUf(String.valueOf(cboxUf.getSelectedItem()));
                fornecedor.setTelefone(numContato);
                fornecedor.setTelefonesecundario(numContatoSec);
                fornecedor.setContato(txtContato.getText());
                fornecedor.setContatosecundario(txtContatoSec.getText());

                if (novo) {
                    if (fornControl.consultarCnpj(ftxtCnpj.getText())) {
                        JOptionPane.showMessageDialog(null, "Há um fornecedor registrado com esse CPF!");
                    } else {
                        fornControl.adicionar(fornecedor);
                        resetarGravar();
                    }
                } else {
                    fornecedor.setCodigo(Integer.parseInt(tableFornecedor.getModel().getValueAt(rowSelectedInTable, 0).toString()));
                    fornControl.atualizar(fornecedor);

                    resetarGravar();
                }
            }
        }
    }

    private void resetarGravar() {
        limparCampos();

        tableFornecedor.setEnabled(true);
        btnNovo.setEnabled(true);
        btnAlterar.setEnabled(true);

        habilitarCampos(false);

        btnGravar.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        txtPesquisa.setEnabled(true);

        listaFornecedor();
    }

    private Component getInstance() {
        return this;
    }

    private void setCampos() {
        rowSelectedInTable = tableFornecedor.getSelectedRow();

        txtNomeFantasia.setText(tableFornecedor.getModel().getValueAt(rowSelectedInTable, 1).toString());
        ftxtCnpj.setText(tableFornecedor.getModel().getValueAt(rowSelectedInTable, 2).toString());
        txtEndereco.setText(tableFornecedor.getModel().getValueAt(rowSelectedInTable, 3).toString());
        txtNumero.setText(tableFornecedor.getModel().getValueAt(rowSelectedInTable, 4).toString());
        txtBairro.setText(tableFornecedor.getModel().getValueAt(rowSelectedInTable, 5).toString());
        txtCidade.setText(tableFornecedor.getModel().getValueAt(rowSelectedInTable, 6).toString());
        ftxtCep.setText(tableFornecedor.getModel().getValueAt(rowSelectedInTable, 7).toString());
        cboxUf.setSelectedItem(tableFornecedor.getModel().getValueAt(rowSelectedInTable, 8));

        String arrayTel[] = (tableFornecedor.getModel().getValueAt(rowSelectedInTable, 9).toString().split(" "));
        ftxtDdd.setText(arrayTel[0]);
        txtTelefone.setText(arrayTel[1]);

        String arrayTelSec[] = (tableFornecedor.getModel().getValueAt(rowSelectedInTable, 10).toString().split(" "));
        ftxtDddSec.setText(arrayTelSec[0]);
        txtTelefoneSec.setText(arrayTelSec[1]);

        txtContato.setText(tableFornecedor.getModel().getValueAt(rowSelectedInTable, 11).toString());
        txtContatoSec.setText(tableFornecedor.getModel().getValueAt(rowSelectedInTable, 12).toString());
    }

//    private void excluir() {
//        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este cliente?", "Atenção", JOptionPane.YES_NO_OPTION);
//
//        if (confirma == JOptionPane.YES_OPTION) {
//            Fornecedor fornecedor = new Fornecedor();
//
//            FornecedorControle fornControl = new FornecedorControle();
//
//            String numContato = ftxtDdd.getText() + " " + txtTelefone.getText();
//            String numContatoSec = ftxtDddSec.getText() + " " + txtTelefoneSec.getText();
//
//            System.out.println(numContato);
//
//            fornecedor.setNomefantasia(txtNomeFantasia.getText());
//            fornecedor.setCnpj(ftxtCnpj.getText());
//            fornecedor.setEndereco(txtEndereco.getText());
//            fornecedor.setNumero(txtNumero.getText());
//            fornecedor.setBairro(txtBairro.getText());
//            fornecedor.setCidade(txtCidade.getText());
//            fornecedor.setCep(ftxtCep.getText());
//            fornecedor.setUf(String.valueOf(cboxUf.getSelectedItem()));
//            fornecedor.setTelefone(numContato);
//            fornecedor.setTelefonesecundario(numContatoSec);
//
//            fornecedor.setCodigo(Integer.parseInt(tableFornecedor.getModel().getValueAt(tableFornecedor.getSelectedRow(), 0).toString()));
//
//            fornControl.excluir(fornecedor);
//
//            limparCampos();
//
//            listaFornecedor();
//        }
//    }
}
